# Derived from:
# https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

name: ARM
on: push

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Build and push
        run: make node-prod && docker buildx build --platform=linux/arm/v7 --tag vector_node_arm:${GITHUB_SHA:0:8} --file modules/server-node/ops/arm.Dockerfile --output type=image,push=true modules/server-node
