# Derived from:
# https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

name: ARM
on: push

jobs:
  build-arm64:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up convenient env vars
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Make
        run: make
      - name: Build ARM and push
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          REGISTRY: docker.io/connextproject
          LOCAL_DEFAULT_IMAGE: vector_node:${CI_SHA_SHORT}
          REMOTE_DEFAULT_IMAGE: ${REGISTRY}/${LOCAL_DEFAULT_IMAGE}
          LOCAL_ARM_IMAGE: vector_node_arm:${CI_SHA_SHORT}
          REMOTE_ARM_IMAGE: ${REGISTRY}/${LOCAL_ARM_IMAGE}
        run: |
          echo "Starting critical step in env:"
          echo "- DOCKER_CLI_EXPERIMENTAL=$DOCKER_CLI_EXPERIMENTAL"
          echo "- REGISTRY=$REGISTRY"
          echo "- LOCAL_DEFAULT_IMAGE=$LOCAL_DEFAULT_IMAGE"
          echo "- REMOTE_DEFAULT_IMAGE=$REMOTE_DEFAULT_IMAGE"
          echo "- LOCAL_ARM_IMAGE=$LOCAL_ARM_IMAGE"
          echo "- REMOTE_ARM_IMAGE=$REMOTE_ARM_IMAGE"
          echo "buildx-ing image name: $REMOTE_ARM_IMAGE"
          echo "buildx-ing image name: ${REMOTE_ARM_IMAGE}"
          echo "buildx-ing image name: ${{REMOTE_ARM_IMAGE}}"
          echo "buildx-ing image name: ${{ env.REMOTE_ARM_IMAGE }}"
          docker buildx build --platform=linux/arm/v7 --tag ${REMOTE_ARM_IMAGE} --file modules/server-node/ops/arm.Dockerfile --output type=image modules/server-node
          echo "(re-?)building server-node"
          make server-node
          echo "docker tag ${LOCAL_DEFAULT_IMAGE} ${REMOTE_DEFAULT_IMAGE}"
          docker tag ${LOCAL_DEFAULT_IMAGE} ${REMOTE_DEFAULT_IMAGE}
          docker push ${REMOTE_DEFAULT_IMAGE}
          digest=$(docker image inspect ${REMOTE_DEFAULT_IMAGE} | jq '.[0].Config.Image' | tr -d '"')
          echo "creating manifest"
          docker manifest create ${REMOTE_DEFAULT_IMAGE} --amend ${REGISTRY}/vector_node@${digest} --amend ${REMOTE_ARM_IMAGE}
