# Derived from:
# https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

name: ARM

on: push

jobs:
  build-arm:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: vector_node_arm
      DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
        echo ::set-output name=version::${GITHUB_SHA:0:8}
    - name: Docker Login
      if: success()
      run: |
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
    - name: Build all the things
      if: success()
      run: make arm
    - name: Run Buildx (push image)
      if: success()
      run: |
        docker buildx build --platform ${{ steps.prepare.outputs.docker_platform }} --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} --file modules/server-node/ops/Dockerfile --output type=image,push=true modules/server-node
