name: Feature Branch

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make all
      - run: make build-report

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make utils
      - run: make test-utils

  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make contracts
      - run: make test-contracts

  test-protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make protocol
      - run: make test-protocol

  test-engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make engine
      - run: make test-engine

  test-node-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make node-server
      - run: make test-node-server
