name: Master

on:
  push:
    branches:
      - master

jobs:

  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make all
      - run: make build-report
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make utils
      - run: make test-utils

  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make contracts
      - run: make test-contracts

  test-protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make protocol
      - run: make test-protocol

  test-node-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make node-server
      - run: make test-node-server
